spring:
  application:
    name: ${artifactId}

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432
    #url: jdvc:postgresql://ip:port/lala
    username: postgres
    password: superUser
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql

server:
  port: 8000

logging:
  lever:
    com.d3: 'DEBUG'