spring:
  application:
    name: ${AppName}
  output:
    ansi:
      enabled: always

  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    url: jdbc:mysql://localhost:3306/${AppName}?useSSL=false
    username: username
    password: password
    enabled: false
  # Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:5432/${AppName}?useSSL=false
    username: username
    password: password
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql

server:
  port: 8000

logging:
  lever:
    com.depp3: 'DEBUG'