spring:
  application:
    name: ${AppName}
  output:
    ansi:
      enabled: always

  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    url: jdbc:mysql://localhost:3306/${AppName}?useSSL=false
    username: username
    password: password
    enabled: false
  # Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:5432/${AppName}?useSSL=false
    username: username
    password: password
    #InMemory
    #driver-class-name: org.h2.Driver
    #username: a
    #password: a
    #url: "jdbc:h2:mem:${AppName};DB_CLOSE_ON_EXIT=FALSE"
  #h2:
    #console:
      #enabled: true
      #path: /h2-console
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql

server:
  port: 8000

logging:
  lever:
    com.depp3: 'DEBUG'